### ISSUE TITLE
Chromosome number in sim_10x_change_output.txt

### ISSUE THREAD

**Issue by ntbeileh** [BDanalysis/aitac#3]
The chromosome number is displaying as just the file name of the reference for me in the sim_10x_change_output11.txt file. What should I change to make it display the actual chromosome number? 

For reference here is my output:
[sim_10x_change_output11.txt](https://github.com/BDanalysis/aitac/files/6698689/sim_10x_change_output11.txt)

Fixed!

**Comment by pinunQ** [comment]
Hey, I am going through the same issue could you explain how did you fix that issue?
